[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routes fallback to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Serve APK/ZIP with correct content types and force download prompt
[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.zip"
  [headers.values]
    Content-Type = "application/zip"
    Content-Disposition = "attachment"
